language: java
jdk: "-openjdk14"
addons:
  sonarcloud:
    organization: "soundmate"
    token:
      secure: "PsymsWkI5/M/Z2iXwJjNHronE/DCbyB9LgcUvPqiPCLYSzoyUBrOwM0LlQJMyG+bYEAJJpdOhi4yUzK4kMsYGp5HYHDMIbzBlmBF0NYtB55VF4val5W3hWoU8/ZM0e9wDWhH045A7UH/PTXzj0HXVzNKN+T4tjLxz9XBAQVsQLpcKEEslybjPWSZhafpxGM23tNCUp2SDS9d+jYG5GzD5lSHzyHm0J98TKbpcm/6++UiY1cBBzC01O4aazb7UjJlRjoCWxgUk2YwNNNRC5E3GNiTTwa2ECfQbnQNzHdk8JVr7W7rm/6WIYTGmbLDOzmALBjAKtkWMaiBc/MewwsszlYkUB1RoWuiHN3g5/IBiwS1pAfdGWeYxPLgURTGd9H60Bi+e1tnT6i/aYmWXjwK5+H/0qI9sqFFlFVaFyEg0x9pBfXS5wvgqVjIvHQ4/CBQxgU0ZgOzLvIJsBfI9h3UbNTUSeNSgDvsy78V5eZKo191w0ZHsRU9i813+rbrmAzF9jj1/3z/UUsmSy/wZznUIxqMsD6dMtitAzgPXLONt9vPmcl9vEZ4w6Y9s//iznYMV0UxcflsjBTVr5TzlKiU5h/zs8zp+LTyfMYu5a1jOMxafBkgMDnlermRzXO+nDNpzB/Sczy1Z/epkO1t5wG6RfO3TwLsZHmJF3NyhCQgrT4=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar