language: java
jdk: "-openjdk14"
addons:
  sonarcloud:
    organization: "soundmate"
    token:
      secure: "NjhfMSuM30A9ch9Ldqpo+3cKDx+SIeIQqe6HdVXoQeIrSV8YTm5yNBYww07xHKBTHyga3uq/WARdAFVu4fMPTIyYLJqNGsh9AdAMD3VZWLSrUXm170l3amWQW58DtI8DupXRUusBwymQq1hEKR/RasSD9dcQWV6MDFI2nLOd+jNQ065TS/hxSbv5e6kf6LsBPuMUvQ02sAw3IFqZMbkXjvsZDaX9I4u/mMTKafoxrjtTJReuazpJcmovkzkwwnVSQcLG4SvjWnE4/k5xPwZIAi1u0uAk880h+RTeUduSgoSnpb6v3HdvTRbH6MfgG9PMAatFUwgXkapZoXr2IXUpq89m7UcFquXbUQbk9sneTCzY/R4hjeA1+GgJiszdE2Cjtu8QfAUXtkwz/XEZbl4EIWHbiDD7mlhbK8Suth5izQH/1XaoaKPr7wAAUxPZpWlJcLH9T5Eb/ncWkaAHSodmMh3g9IGBzfqK9PnIzKy6fftYL3xzNmpdvUYesKZyLjsPHW/rWxy9NU0PeHN0XHrq+TKw9VMaoYbGNdJk5JzFindulu4cjSwrJ+Bdh92oazK2dVaYJasjM2Yias1UZgBuo/BP3NsXiYV6ksK4EkgZ/3prC3a0rU6g6U4pRqmcA5A7z6aNCtFYd+AaW3hFVNIOuZIN5rZeSYiupLnbVkPPwDQ=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar -Dsonar.projectKey=SoundMate_SoundmateFX