language: java
jdk: "-openjdk14"
addons:
  sonarcloud:
    organization: "soundmate"
    token:
      secure: "n91pbf/kTHaAUglx3C4mqGW2Iy8AgdoDlmjDfRPhLiEpa8rHDlyoJB6ZRNOx0mJYwM57WcHZyiYto6Dc8akXbTO9Pz2b4M5gyNCEsZKHyMrfS2NatWU8E99e6ygWScuAI63Tzehy97uOFm2V7alYztc2gMWaYnc3qPylhv0LAdP4nsrg2lOPf0L5X8Fd3cd3yGkBJIEiS6Jz6Ia0Q9/tc9m8Qdp8hzpRdy0T7K9E8JdluqjdhJmQxaAMkgaQj4bRuGKurU/rTg35qo3q/JA6SSvKyb/+VYyXBt6G8vDJsSHtM9JqCV3JyJsJqFw1qM4HTHYIO2x1LAyKt5V2oKKgqt2V14ei2EQulSWV5aBUb/Q3hMikNko51fohNjMbSeOtl8qFGCmqpMxHUyBsw5rSu74PGrYbwZ5SNlyHjLfyf6LAYpffeMieUcsiBCQ6tnsCsIQj+G6RUwRHUlYvPfKY/4WCnLxxU84YXiisN0R2HPdqQYRTOU0VaWURu+tAMN8jkC7mUEgkd4NnGeQ7gzu0LO5jy3wIfizkkXRmfss609yRZ87+08LCK7zV0TiGxHocRxEIb1NPcsELOM9IQA6jIaC0YNmUOD5OJIuJWQxdE78/ZzFxaZsyK9mochmIt5JAUq97d6Hj+X/XQvxm8iLC4rb/VyqYi9VaTohU+hL4UGI=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SoundMate_SoundmateFX