language: java
jdk: "-openjdk14"
addons:
  sonarcloud:
    organization: "soundmate"
    token:
      secure: "g7p3Jj34D3ToNlejBQpv1s8oyTH3lFnJOCTHKabnbs+j+UqXJy67g3RORww6Lt9GpEKaOgstBCb4pR5UnebE6W8BCdoSPcBQCGl6KsuN7g/wRpptVlRZfALX28sSWGqHa+Z+nSzGZH13A6bT2IF771rJ3KukLOUDqv+lcOPSauZOsWagc07+LUwXT8Qln4f66wkh1geN39j6dNSXY0tJjehebFvxB9VBFBcTkrupZGGJWUq8Uk2saQ01K+EYV0Y56P4Kt318CJPv97dwyX0TZXKcUiBBGmzGdGEF3h1+m7vPOw7qG6rUDZIr7HblkNNf/tZIA08D/BI4WH3u9pTA24aq4p6fwUxGBV7FYXVj7uhQQax8+E/OqZUBrFgP6r/6btmIs0H3eOJfUZEntpn3pl4+yHOu820A0Z74wSzMM9wzVM43oPefu7ap2qNVV+0iLFYT5/81wK2nwZb1ZUcUyY5K0H58O6uhuPVcvesFQPQ6Du3ClWBXotdbmVOaGfQ8MfTmWnIkLrhkjQmlVCqqRlz992Rir8zIPSbyJoB0HCs+6ZhMT0iogzV1Cod3XKlZqZ+Y8QykpIXLaCVAJ5+G/b6rBdPRt912AKhuR1IISfXbtIJX3rknVICSkbgL1+YLzxq3QiFTdfe6u3yEB3S3qjLCWr5EU0PVaxrueTSg1tc=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install